# Generated by Django 5.0.4 on 2024-05-17 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Product name can only contain letters, numbers, spaces, '?','&', '!', '^','-','_','.', hyphens, and apostrophe characters.", regex="^[A-Za-z0-9?!,.\\'\\s-]+$")])),
                ('description', models.TextField()),
                ('image_1', models.ImageField(default='', upload_to='Recommended')),
                ('image_2', models.ImageField(default='', upload_to='Recommended')),
                ('image_3', models.ImageField(default='', upload_to='Recommended')),
                ('image_4', models.ImageField(default='', upload_to='Recommended')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], default=False, max_length=1)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Product')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.orderdetail', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Detail Item',
                'verbose_name_plural': 'Order Detail Items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=255, validators=[django.core.validators.RegexValidator(message="Product name can only contain letters, numbers, spaces, '?', '!', ',', '.', hyphens, and apostrophe characters.", regex="^[A-Za-z0-9?!,.\\'\\s-]+$")])),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='Product')),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('size', models.CharField(default=False, max_length=10)),
                ('price', models.IntegerField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'product', 'size')},
            },
        ),
    ]
